// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0gZv-68Q8oXLBzuVfckvkHJh1s9CZIY',
    appId: '1:1057591596440:web:9b39c83fb852bd9460c7ed',
    messagingSenderId: '1057591596440',
    projectId: 'spark-23d2c',
    authDomain: 'spark-23d2c.firebaseapp.com',
    storageBucket: 'spark-23d2c.firebasestorage.app',
    measurementId: 'G-EXTBHJE5X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoOfYgfToqqW3zNfesy70h1NyFeVqtqU',
    appId: '1:1057591596440:android:14b6157db4650af660c7ed',
    messagingSenderId: '1057591596440',
    projectId: 'spark-23d2c',
    storageBucket: 'spark-23d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3tvjzHj6uIvIyYmUXzZFyBUqfMPhBJQ',
    appId: '1:1057591596440:ios:14d9e28eb36591f860c7ed',
    messagingSenderId: '1057591596440',
    projectId: 'spark-23d2c',
    storageBucket: 'spark-23d2c.firebasestorage.app',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3tvjzHj6uIvIyYmUXzZFyBUqfMPhBJQ',
    appId: '1:1057591596440:ios:14d9e28eb36591f860c7ed',
    messagingSenderId: '1057591596440',
    projectId: 'spark-23d2c',
    storageBucket: 'spark-23d2c.firebasestorage.app',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR0gZv-68Q8oXLBzuVfckvkHJh1s9CZIY',
    appId: '1:1057591596440:web:20145faa1980c5dd60c7ed',
    messagingSenderId: '1057591596440',
    projectId: 'spark-23d2c',
    authDomain: 'spark-23d2c.firebaseapp.com',
    storageBucket: 'spark-23d2c.firebasestorage.app',
    measurementId: 'G-3GRWN5WG8B',
  );
}
